### ISSUE TITLE
Why closed source

### ISSUE THREAD

**Issue by FlorianGrimm** [devlooped/SponsorLink#19]
Why is this closed source?

Please make this open source so we can still use your packages. Like Moq or ThisAssembly.

**Comment by kzu** [comment]
Yep, on it. I need to unify the commit history of this repo with the one containing the source. Doing that today.

Thanks!

**Comment by kzu** [comment]
Full OSS for SponsorLink (including client and backend) now lives in this same repo, under the `src` folder.

Thanks!
