### ISSUE TITLE
SponsorLink must NEVER be obfuscated

### ISSUE THREAD

**Issue by ckuetbach** [devlooped/SponsorLink#36]
## Describe the Bug

SponsolLink is embedded as obfuscated DLL within packages like any virus would be.

## Steps to Reproduce

Look into any SponsorLink package available

## Expected Behavior

A security official in a company can review the decompiled) source of suspicious looking network traffic and review the packages to rule out leak of secrets, API keys or internectual properties. 

## Version Info

Every version available

**Comment by kzu** [comment]
It's OSS now. It won't be obfuscated in any future versions. And the current versions in nuget.org will be updated soon. The published (formerly obfuscated binary) comes from this same source code.

**Comment by kzu** [comment]
Fixed in https://www.nuget.org/packages/Devlooped.SponsorLink/1.1.0
