### ISSUE TITLE
autisync link is broken on page https://github.com/devlooped#autosync

### ISSUE THREAD

**Issue by alexey-leonovich** [devlooped/SponsorLink#379]
> You can simplify this process by enabling [autosync](https://www.devlooped.com/SponsorLink/github.html#auto-sync) so that the IDE tooling can ...

Correct link for today is [autosync](https://www.devlooped.com/SponsorLink/github#auto-sync)

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Good catch, thanks!
