### ISSUE TITLE
Devlooped.SponsorLink analyzer should not contain obfuscated code

### ISSUE THREAD

**Issue by sharwell** [devlooped/SponsorLink#9]
See the title. Users need to be able to understand the code being injected into a build. This is important for transparency and trust.

**Comment by kzu** [comment]
That would make it trivial to bypass the SponsorLink check. So, this is by design at this point unless there's serious concerns raised by a large portion of users.

**Comment by NickMOrlando** [comment]
> That would make it trivial to bypass the SponsorLink check. So, this is by design at this point unless there's serious concerns raised by a large portion of users.

What constitutes a large portion of users?

The introduction of this package into Moq has spawned [a significant number of concerns ](https://github.com/moq/moq/issues/1372) over that package's viability in any F/OSS or Corporate environment.

**Comment by CryoMyst** [comment]
Developers are not going to accept telemetry without transparency.

**Comment by Atulin** [comment]
"Trust me bro" isn't much of an assurance when it comes to running arbitrary code on the user's machine.

**Comment by cygnim** [comment]
@kzu I'd say serious concerns have now been raised. The vast majority of users don't even know this change has been made and would have a problem. Trust with moq is now broken as has GDPR. This is underhanded to say the least. Be one the good guys.

**Comment by Ibmurai** [comment]
> That would make it trivial to bypass the SponsorLink check. So, this is by design at this point unless there's serious concerns raised by a large portion of users.

Why should it not be trivial to bypass?

**Comment by kzu** [comment]
Because if it's trivial to bypass, nobody would donate and we'd be back to the same situation that sparked the desire to get funding?

Yes, I'd consider serious concerns have been raised. I'm evaluating bringing the analyzer code over to this repo. I'd like to bring it with its commit history so that it's clear how it came about too. Need to brush up my git-fu :)

**Comment by cygnim** [comment]
I think the point is, this funding model is inherently dishonest and should be abandoned immediately.

**Comment by ScarletKuro** [comment]
> Because if it's trivial to bypass, nobody would donate and we'd be back to the same situation that sparked the desire to get funding?

Any skilled .NET engineer possesses the capability to bypass through this obfuscated code. I am convinced that any motivated individual could do so, as even dead de4dot can still dismantle a portion of the obfuscation present in the DLL, also replacing some IL code is not a problem nowadays as well. However, I'm skeptical that any reputable software engineer would do it, but if they do, I doubt they would sponsor whoever uses `Devlooped.SponsorLink` anyway.

This is not the main point tho. By obfuscating and keeping the source code closed, you create a barrier for audits, especially in highly secure environments. You are attempting to conceal the inner workings of your program, but there is no assurance that a future update of `Devlooped.SponsorLink` won't introduce unexpected elements, such as a Bitcoin miner(just an example). Sadly, I've come across numerous of paid software developed by individuals that contain hidden backdoors to take revenge if something happens.

I strongly believe that projects like these libraries should prioritize transparency. The primary goal of this library should revolve around capturing developers' attention, highlighting its donation avenues, and encouraging sponsorship if feasible. This is why I'm puzzled by the idea of obfuscation – after all, those uninterested in sponsoring won't be swayed regardless.

**Comment by wdolek** [comment]
> Because if it's trivial to bypass, nobody would donate and we'd be back to the same situation that sparked the desire to get funding?

It's easier to send few bucks than trying to figure out how to bypass message somewhere (even trivial one). Even your obfuscated closed source solution can be bypassed after all 🤷 - this cannot justify malware-ish behaviour of this library.

**Comment by NiKiZe** [comment]
Any obfuscated analyser should be treated as virus/spyware. Will be blocking and reporting.

**Comment by kzu** [comment]
Analyzer and backend is all OSS in this repo now too. Locking this thread as a consequence.
